// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekTrashVision.Data;

#nullable disable

namespace ProjekTrashVision.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RiwayatDeteksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LabelHasil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NamaFile")
                        .HasColumnType("longtext");

                    b.Property<float>("SkorKeyakinan")
                        .HasColumnType("float");

                    b.Property<DateTime>("WaktuUpload")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("RiwayatDeteksis");
                });
#pragma warning restore 612, 618
        }
    }
}
